### ISSUE TITLE
A book disappeared

### ISSUE THREAD

**Issue by hakob21** [Philantrop/calibre-marvin-manager#56]
Hi. I'm having this problem the second time already (first was on another laptop), with the same book, which is kinda odd. But, anyway, I installed Marvin XD plugin and wanted to check out how it works with annotations. I made a test annotation in the book "The Wonderful Wizard of Oz". Before making that, the plugin saw all 5 books in Marvin app on my iPad (including Oz), but after that it showed only the other 4 books. I though maybe it has something to do with that annotation and deleted it, but still nothing. Then I made some in the other book and this time it worked fine, all the vocabulary word and annotations in that book could be copied using the plugin. So, it's like the first book just disappeared no matter with or without any annotations. Thanks for attention. Hope you'll help me. 

Device: iPad 2 64gb 3g
Calibre Version: 1.44
Marvin XD, iOS reader application and Marvin ios app are all up to date

**Comment by Philantrop** [comment]
No response, closing.
