### ISSUE TITLE
Add info to the Readme?

### ISSUE THREAD

**Issue by strider72** [Philantrop/calibre-marvin-manager#62]
I don't actually know what this program does because you say so little in the Readme.  I think you're assuming people finding this page will already know about the project.

Is it a plugin for a different app (calibre)?  A command-line utility?

**Comment by strider72** [comment]
Okay... I found the about.txt; but why not just put this in the Readme so it appears on the GitHub page?

**Comment by Philantrop** [comment]
Good idea, thanks, done.
