### ISSUE TITLE
Marvin icon not displaying on Calibre menu bar

### ISSUE THREAD

**Issue by mlbeeker** [Philantrop/calibre-marvin-manager#64]
I believe I've followed all instructions at: http://www.mobileread.com/forums/showthread.php?t=241145
but am not seeing the Marvin icon appear in Calibre when I connect the iPad and start Calibre,

Here is what I'm using and a few things I did to try to solve the problem.  Thanks for any help...
iPad
  Version 9.1 (13B143)
  Carrier: AT&T 22.0
  Model: MF012LL/
Marvin version 2.8.5
Marvin XD version 1.2.4
Calibre 2.44 running (917 books)
Windows 10 Home 64-bit operating system, x64-based processor
iOS reader applications 1.4.7.0.0 (with Marvin as preferred iOS reader)

I've tried:
* Un-installing and re-installing iOS Reader Applications & Marvin XD plugins 
* Disabling the Apple iTunes Interface (1.1.1) in the Calibre > Preferences> Plugins >
* Various permutations of turning off devices and applications (after following the exact process suggested for installing and operation)
* In iTunes, I checked "Prevent iPods, iPhones (etc) from syncing automatically"
* Made sure wi-fi syncing is disabled
* iPad has been reset several times
* USB cable has been traded out

(aside which might be related (?): I initially had a problem with the iPad drivers provided by Microsoft not being up-to-date, so iTunes wasn't recognizing when the iPad was connected.  I updated driver to version 10.0.10240.16431 and the iPad now displays in iTunes as a connected device.)

If it's helpful, on Windows Task Manager the following processes are running:
* Apps: "The main calibre program (32 bit)"
* Background processes: "calibre worker process (32 bit)"

**Comment by Philantrop** [comment]
If only you had not only read that thread but the huge red letters at its very beginning:

This plugin is NOT compatible with iOS >= 8.3. Nothing can be done about it till Marvin itself is adapted to the changes by Apple.

**Comment by mlbeeker** [comment]
Sorry about that -- I mis-read the notice and thought it said just OS.

- Mary

On Sun, Nov 15, 2015 at 5:20 PM, Wulf C. Krueger <notifications@github.com>
wrote:

> If only you had not only read that thread but the huge red letters at its
> very beginning:
>
> This plugin is NOT compatible with iOS >= 8.3. Nothing can be done about
> it till Marvin itself is adapted to the changes by Apple.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Philantrop/calibre-marvin-manager/issues/64#issuecomment-156864056>
> .
>



-- 
Mary Beeker
mlbeeker@gmail.com
